PUZZLE_BANK = [
    # -------------------------------
    # ARTICLES OF FAITH
    # -------------------------------
    {"category": "Articles of Faith", "text": "BELIEF IN GOD AND THE HOLY GHOST", "reference": "John 14:26"},
    {"category": "Articles of Faith", "text": "MEN PUNISHED FOR OWN SINS", "reference": "Ezekiel 18:20"},
    {"category": "Articles of Faith", "text": "SALVATION THROUGH CHRIST", "reference": "Acts 4:12"},
    {"category": "Articles of Faith", "text": "FIRST PRINCIPLES AND ORDINANCES", "reference": "Hebrews 6:1-2"},
    {"category": "Articles of Faith", "text": "CALLED OF GOD BY PROPHECY", "reference": "Hebrews 5:4"},
    {"category": "Articles of Faith", "text": "PRIMITIVE CHURCH ORGANIZATION", "reference": "Ephesians 4:11-12"},
    {"category": "Articles of Faith", "text": "SPIRITUAL GIFTS LIKE PROPHECY", "reference": "1 Corinthians 12:7-10"},
    {"category": "Articles of Faith", "text": "BIBLE AND BOOK OF MORMON", "reference": "Ezekiel 37:16-17"},
    {"category": "Articles of Faith", "text": "GOD REVEALS MANY THINGS", "reference": "Amos 3:7"},
    {"category": "Articles of Faith", "text": "GATHERING OF ISRAEL", "reference": "Isaiah 11:12"},
    {"category": "Articles of Faith", "text": "WORSHIP ACCORDING TO CONSCIENCE", "reference": "Articles of Faith 11"},
    {"category": "Articles of Faith", "text": "OBEY AND HONOR THE LAW", "reference": "Articles of Faith 12"},
    {"category": "Articles of Faith", "text": "SEEK VIRTUE AND PRAISEWORTHY THINGS", "reference": "Philippians 4:8"},

    # -------------------------------
    # DOCTRINE & COVENANTS
    # -------------------------------
    {"category": "Doctrine & Covenants", "text": "JOSEPH SMITH SAW TWO PERSONAGES", "reference": "Joseph Smith—History 1:17"},
    {"category": "Doctrine & Covenants", "text": "TRUE AND LIVING CHURCH", "reference": "Doctrine & Covenants 1:30"},
    {"category": "Doctrine & Covenants", "text": "GOD'S VOICE OR HIS SERVANTS", "reference": "Doctrine & Covenants 1:38"},
    {"category": "Doctrine & Covenants", "text": "LOOK TO CHRIST; DOUBT NOT", "reference": "Doctrine & Covenants 6:36"},
    {"category": "Doctrine & Covenants", "text": "REVELATION BY HOLY GHOST", "reference": "Doctrine & Covenants 8:2-3"},
    {"category": "Doctrine & Covenants", "text": "KEYS OF AARONIC PRIESTHOOD", "reference": "Doctrine & Covenants 13:1"},
    {"category": "Doctrine & Covenants", "text": "WORTH OF SOULS IS GREAT", "reference": "Doctrine & Covenants 18:10"},
    {"category": "Doctrine & Covenants", "text": "JOY IN BRINGING SOULS TO CHRIST", "reference": "Doctrine & Covenants 18:15-16"},
    {"category": "Doctrine & Covenants", "text": "CHRIST SUFFERED FOR ALL", "reference": "Doctrine & Covenants 19:16-19"},
    {"category": "Doctrine & Covenants", "text": "RECEIVE PROPHET'S WORD AS GOD'S", "reference": "Doctrine & Covenants 21:5"},
    {"category": "Doctrine & Covenants", "text": "CHRIST WILL REVEAL HIMSELF", "reference": "Doctrine & Covenants 76:22-24"},
    {"category": "Doctrine & Covenants", "text": "MARRIAGE ORDAINED OF GOD", "reference": "Doctrine & Covenants 49:15"},
    {"category": "Doctrine & Covenants", "text": "REPENTED IS FORGIVEN", "reference": "Doctrine & Covenants 58:42"},
    {"category": "Doctrine & Covenants", "text": "FORGIVE ALL MEN", "reference": "Doctrine & Covenants 64:10"},
    {"category": "Doctrine & Covenants", "text": "WORLDS CREATED BY CHRIST", "reference": "Doctrine & Covenants 76:22-24"},
    {"category": "Doctrine & Covenants", "text": "LORD IS BOUND BY OBEDIENCE", "reference": "Doctrine & Covenants 82:10"},
    {"category": "Doctrine & Covenants", "text": "POWER OF GODLINESS IN ORDINANCES", "reference": "Doctrine & Covenants 84:20-21"},
    {"category": "Doctrine & Covenants", "text": "LEARN BY STUDY AND FAITH", "reference": "Doctrine & Covenants 88:118"},
    {"category": "Doctrine & Covenants", "text": "WORD OF WISDOM BLESSINGS", "reference": "Doctrine & Covenants 89:18-21"},
    {"category": "Doctrine & Covenants", "text": "MELCHIZEDEK PRIESTHOOD SPIRITUAL KEYS", "reference": "Doctrine & Covenants 107:18-19"},
    {"category": "Doctrine & Covenants", "text": "PRIESTHOOD OPERATES BY RIGHTEOUSNESS", "reference": "Doctrine & Covenants 121:36"},
    {"category": "Doctrine & Covenants", "text": "FATHER AND SON HAVE BODIES", "reference": "Doctrine & Covenants 130:22"},
    {"category": "Doctrine & Covenants", "text": "NEW AND EVERLASTING COVENANT", "reference": "Doctrine & Covenants 132:19"},
    {"category": "Doctrine & Covenants", "text": "JOSEPH SMITH BROUGHT FORTH BOOK OF MORMON", "reference": "Doctrine & Covenants 135:3"},

        # -------------------------------
    # OLD TESTAMENT PROPHETS
    # -------------------------------
    {"category": "Old Testament Prophets", "text": "GOD'S WORK AND GLORY IS TO BRING TO PASS IMMORTALITY AND ETERNAL LIFE", "reference": "Moses 1:39"},
    {"category": "Old Testament Prophets", "text": "ZION IS OF ONE HEART AND ONE MIND", "reference": "Moses 7:18"},
    {"category": "Old Testament Prophets", "text": "ABRAHAM'S SEED WILL BEAR THE PRIESTHOOD TO ALL NATIONS", "reference": "Abraham 2:9–11"},
    {"category": "Old Testament Prophets", "text": "SPIRITS WERE ORGANIZED BEFORE THE WORLD WAS", "reference": "Abraham 3:22–23"},
    {"category": "Old Testament Prophets", "text": "GOD CREATED MAN IN HIS OWN IMAGE", "reference": "Genesis 1:26–27"},
    {"category": "Old Testament Prophets", "text": "A MAN SHALL CLEAVE UNTO HIS WIFE AND BE ONE", "reference": "Genesis 2:24"},
    {"category": "Old Testament Prophets", "text": "JOSEPH RESISTED TEMPTATION, REFUSING TO SIN AGAINST GOD", "reference": "Genesis 39:9"},
    {"category": "Old Testament Prophets", "text": "THE TEN COMMANDMENTS", "reference": "Exodus 20:3–17"},
    {"category": "Old Testament Prophets", "text": "CHOOSE YOU THIS DAY WHOM YE WILL SERVE", "reference": "Joshua 24:15"},
    {"category": "Old Testament Prophets", "text": "WHO SHALL STAND IN GOD'S HOLY PLACE?", "reference": "Psalm 24:3–4"},
    {"category": "Old Testament Prophets", "text": "TRUST IN THE LORD WITH ALL YOUR HEART", "reference": "Proverbs 3:5–6"},
    {"category": "Old Testament Prophets", "text": "THOUGH SINS BE AS SCARLET, THEY CAN BE WHITE AS SNOW", "reference": "Isaiah 1:18"},
    {"category": "Old Testament Prophets", "text": "WOE UNTO THEM THAT CALL EVIL GOOD AND GOOD EVIL", "reference": "Isaiah 5:20"},
    {"category": "Old Testament Prophets", "text": "A MARVELOUS WORK AND A WONDER", "reference": "Isaiah 29:13–14"},
    {"category": "Old Testament Prophets", "text": "CHRIST BORE OUR GRIEFS AND CARRIED OUR SORROWS", "reference": "Isaiah 53:3–5"},
    {"category": "Old Testament Prophets", "text": "BLESSINGS OF A PROPER FAST", "reference": "Isaiah 58:6–7"},
    {"category": "Old Testament Prophets", "text": "CALL THE SABBATH A DELIGHT", "reference": "Isaiah 58:13–14"},
    {"category": "Old Testament Prophets", "text": "BEFORE I FORMED THEE, I ORDAINED THEE A PROPHET", "reference": "Jeremiah 1:4–5"},
    {"category": "Old Testament Prophets", "text": "THE PROPHET IS A WATCHMAN UNTO THE HOUSE OF ISRAEL", "reference": "Ezekiel 3:16–17"},
    {"category": "Old Testament Prophets", "text": "THE BIBLE AND BOOK OF MORMON SHALL BECOME ONE", "reference": "Ezekiel 37:15–17"},
    {"category": "Old Testament Prophets", "text": "GOD WILL SET UP A KINGDOM THAT WILL NEVER BE DESTROYED", "reference": "Daniel 2:44–45"},
    {"category": "Old Testament Prophets", "text": "THE LORD REVEALS HIS SECRETS TO HIS PROPHETS", "reference": "Amos 3:7"},
    {"category": "Old Testament Prophets", "text": "BLESSINGS OF PAYING TITHING", "reference": "Malachi 3:8–10"},
    {"category": "Old Testament Prophets", "text": "ELIJAH WILL TURN THE HEARTS OF THE CHILDREN TO THEIR FATHERS", "reference": "Malachi 4:5–6"},

        # -------------------------------
    # NEW TESTAMENT
    # -------------------------------
    {"category": "New Testament", "text": "LET YOUR LIGHT SHINE", "reference": "Matthew 5:14–16"},
    {"category": "New Testament", "text": "COME UNTO ME", "reference": "Matthew 11:28–30"},
    {"category": "New Testament", "text": "KEYS OF THE KINGDOM", "reference": "Matthew 16:15–19"},
    {"category": "New Testament", "text": "LOVE GOD AND NEIGHBOR", "reference": "Matthew 22:36–39"},
    {"category": "New Testament", "text": "CHRIST IS BORN", "reference": "Luke 2:10–12"},
    {"category": "New Testament", "text": "PARTAKE OF SACRAMENT", "reference": "Luke 22:19–20"},
    {"category": "New Testament", "text": "CHRIST HAS FLESH AND BONES", "reference": "Luke 24:36–39"},
    {"category": "New Testament", "text": "BORN OF WATER AND SPIRIT", "reference": "John 3:5"},
    {"category": "New Testament", "text": "GOD SO LOVED THE WORLD", "reference": "John 3:16"},
    {"category": "New Testament", "text": "KNOW THE DOCTRINE", "reference": "John 7:17"},
    {"category": "New Testament", "text": "LIFE ETERNAL", "reference": "John 17:3"},
    {"category": "New Testament", "text": "BODY IS A TEMPLE", "reference": "1 Corinthians 6:19–20"},
    {"category": "New Testament", "text": "MAN AND WOMAN IN THE LORD", "reference": "1 Corinthians 11:11"},
    {"category": "New Testament", "text": "IN CHRIST SHALL ALL BE ALIVE", "reference": "1 Corinthians 15:20–22"},
    {"category": "New Testament", "text": "DEGREES OF GLORY", "reference": "1 Corinthians 15:40–42"},
    {"category": "New Testament", "text": "GATHER TOGETHER IN CHRIST", "reference": "Ephesians 1:10"},
    {"category": "New Testament", "text": "CHURCH BUILT ON APOSTLES", "reference": "Ephesians 2:19–20"},
    {"category": "New Testament", "text": "FALLING AWAY BEFORE CHRIST", "reference": "2 Thessalonians 2:1–3"},
    {"category": "New Testament", "text": "HOLY SCRIPTURES MAKE WISE", "reference": "2 Timothy 3:15–17"},
    {"category": "New Testament", "text": "FATHER OF SPIRITS", "reference": "Hebrews 12:9"},
    {"category": "New Testament", "text": "ASK GOD FOR WISDOM", "reference": "James 1:5–6"},
    {"category": "New Testament", "text": "FAITH WITHOUT WORKS IS DEAD", "reference": "James 2:17–18"},
    {"category": "New Testament", "text": "GOSPEL PREACHED TO DEAD", "reference": "1 Peter 4:6"},
    {"category": "New Testament", "text": "DEAD JUDGED BY WORKS", "reference": "Revelation 20:12"},

    # -------------------------------
    # BOOK OF MORMON
    # -------------------------------
    {"category": "Book of Mormon", "text": "I WILL GO AND DO", "reference": "1 Nephi 3:7"},
    {"category": "Book of Mormon", "text": "MEN ARE THAT THEY MIGHT HAVE JOY", "reference": "2 Nephi 2:25"},
    {"category": "Book of Mormon", "text": "FREE TO CHOOSE LIBERTY OR DEATH", "reference": "2 Nephi 2:27"},
    {"category": "Book of Mormon", "text": "ALL ARE ALIKE UNTO GOD", "reference": "2 Nephi 26:33"},
    {"category": "Book of Mormon", "text": "LINE UPON LINE", "reference": "2 Nephi 28:30"},
    {"category": "Book of Mormon", "text": "FEAST UPON WORDS OF CHRIST", "reference": "2 Nephi 32:3"},
    {"category": "Book of Mormon", "text": "PRAY ALWAYS", "reference": "2 Nephi 32:8–9"},
    {"category": "Book of Mormon", "text": "SERVICE TO GOD", "reference": "Mosiah 2:17"},
    {"category": "Book of Mormon", "text": "KEEP COMMANDMENTS AND BE BLESSED", "reference": "Mosiah 2:41"},
    {"category": "Book of Mormon", "text": "PUT OFF THE NATURAL MAN", "reference": "Mosiah 3:19"},
    {"category": "Book of Mormon", "text": "BELIEVE IN GOD", "reference": "Mosiah 4:9"},
    {"category": "Book of Mormon", "text": "BAPTISM IS A COVENANT", "reference": "Mosiah 18:8–10"},
    {"category": "Book of Mormon", "text": "CHRIST SUFFERED ALL PAINS", "reference": "Alma 7:11–13"},
    {"category": "Book of Mormon", "text": "INFINITE ATONEMENT", "reference": "Alma 34:9–10"},
    {"category": "Book of Mormon", "text": "LUSTS OF YOUR EYES", "reference": "Alma 39:9"},
    {"category": "Book of Mormon", "text": "WICKEDNESS NEVER WAS HAPPINESS", "reference": "Alma 41:10"},
    {"category": "Book of Mormon", "text": "BUILD ON THE ROCK OF CHRIST", "reference": "Helaman 5:12"},
    {"category": "Book of Mormon", "text": "CHRIST DID THE FATHER'S WILL", "reference": "3 Nephi 11:10–11"},
    {"category": "Book of Mormon", "text": "BE PERFECT LIKE GOD", "reference": "3 Nephi 12:48"},
    {"category": "Book of Mormon", "text": "BE SANCTIFIED BY HOLY GHOST", "reference": "3 Nephi 27:20"},
    {"category": "Book of Mormon", "text": "TRIAL OF YOUR FAITH", "reference": "Ether 12:6"},
    {"category": "Book of Mormon", "text": "WEAK THINGS MADE STRONG", "reference": "Ether 12:27"},
    {"category": "Book of Mormon", "text": "CHARITY IS PURE LOVE OF CHRIST", "reference": "Moroni 7:45–48"},
    {"category": "Book of Mormon", "text": "HOLY GHOST REVEALS TRUTH", "reference": "Moroni 10:4–5"},
]
