italian_set = {
    # --- Greetings & Basics ---
    "hello": "ciao",
    "hi": "salve",
    "good morning": "buongiorno",
    "good evening": "buonasera",
    "good night": "buonanotte",
    "please": "per favore",
    "thank you": "grazie",
    "thanks a lot": "grazie mille",
    "you're welcome": "prego",
    "excuse me": "mi scusi",
    "sorry": "mi dispiace",
    "how are you": "come stai",
    "I'm fine": "sto bene",
    "nice to meet you": "piacere di conoscerti",
    "see you later": "a dopo",
    "see you soon": "a presto",
    "goodbye": "arrivederci",
    "welcome": "benvenuto",

    # --- Useful Phrases ---
    "I don't understand": "non capisco",
    "do you speak English": "parli inglese",
    "I need help": "ho bisogno di aiuto",
    "where is the bathroom": "dov'è il bagno",
    "how much does it cost": "quanto costa",
    "I would like this": "vorrei questo",
    "can you repeat": "puoi ripetere",
    "what time is it": "che ore sono",
    "I'm lost": "mi sono perso",
    "I'm hungry": "ho fame",
    "I'm thirsty": "ho sete",
    "I'm tired": "sono stanco",
    "I'm cold": "ho freddo",
    "I'm hot": "ho caldo",
    "I'm sick": "sono malato",
    "I feel good": "mi sento bene",
    "I feel bad": "mi sento male",
    "I don't know": "non so",
    "I think so": "penso di sì",
    "I don't think so": "non penso",
    "it's okay": "va bene",
    "no problem": "nessun problema",
    "of course": "certo",
    "one moment": "un momento",
    "I'm in a hurry": "ho fretta",
    "I'm just looking": "sto solo guardando",

    # --- Nouns (People) ---
    "man": "uomo",
    "woman": "donna",
    "child": "bambino",
    "boy": "ragazzo",
    "girl": "ragazza",
    "friend": "amico",
    "family": "famiglia",
    "mother": "madre",
    "father": "padre",
    "brother": "fratello",
    "sister": "sorella",
    "son": "figlio",
    "daughter": "figlia",
    "husband": "marito",
    "wife": "moglie",
    "teacher": "insegnante",
    "student": "studente",
    "doctor": "medico",
    "nurse": "infermiere",
    "police officer": "poliziotto",

    # --- Nouns (Places) ---
    "house": "casa",
    "apartment": "appartamento",
    "hotel": "albergo",
    "room": "camera",
    "restaurant": "ristorante",
    "bar": "bar",
    "store": "negozio",
    "supermarket": "supermercato",
    "market": "mercato",
    "school": "scuola",
    "church": "chiesa",
    "hospital": "ospedale",
    "pharmacy": "farmacia",
    "airport": "aeroporto",
    "train station": "stazione",
    "bus stop": "fermata dell'autobus",
    "city": "città",
    "town": "paese",
    "street": "strada",
    "square": "piazza",
    "park": "parco",
    "bank": "banca",
    "post office": "ufficio postale",

    # --- Nouns (Objects) ---
    "car": "macchina",
    "bus": "autobus",
    "train": "treno",
    "bicycle": "bicicletta",
    "phone": "telefono",
    "computer": "computer",
    "table": "tavolo",
    "chair": "sedia",
    "bed": "letto",
    "door": "porta",
    "window": "finestra",
    "bag": "borsa",
    "wallet": "portafoglio",
    "ticket": "biglietto",
    "key": "chiave",
    "book": "libro",
    "pen": "penna",
    "paper": "carta",
    "money": "soldi",
    "credit card": "carta di credito",

    # --- Nouns (Food & Drink) ---
    "water": "acqua",
    "sparkling water": "acqua frizzante",
    "coffee": "caffè",
    "tea": "tè",
    "milk": "latte",
    "bread": "pane",
    "cheese": "formaggio",
    "meat": "carne",
    "fish": "pesce",
    "fruit": "frutta",
    "vegetables": "verdure",
    "apple": "mela",
    "banana": "banana",
    "orange": "arancia",
    "rice": "riso",
    "pasta": "pasta",
    "pizza": "pizza",
    "salad": "insalata",
    "soup": "zuppa",
    "dessert": "dolce",

    # --- Verbs (Common) ---
    "to be": "essere",
    "to have": "avere",
    "to go": "andare",
    "to come": "venire",
    "to do": "fare",
    "to make": "fare",
    "to eat": "mangiare",
    "to drink": "bere",
    "to see": "vedere",
    "to hear": "sentire",
    "to speak": "parlare",
    "to read": "leggere",
    "to write": "scrivere",
    "to sleep": "dormire",
    "to work": "lavorare",
    "to study": "studiare",
    "to buy": "comprare",
    "to pay": "pagare",
    "to help": "aiutare",
    "to wait": "aspettare",
    "to start": "iniziare",
    "to finish": "finire",
    "to walk": "camminare",
    "to run": "correre",
    "to drive": "guidare",
    "to live": "vivere",
    "to love": "amare",
    "to think": "pensare",
    "to believe": "credere",
    "to feel": "sentire",
    "to find": "trovare",
    "to give": "dare",
    "to take": "prendere",
    "to call": "chiamare",
    "to ask": "chiedere",
    "to answer": "rispondere",
    "to open": "aprire",
    "to close": "chiudere",
    "to bring": "portare",
    "to use": "usare",
    "to try": "provare",
    "to learn": "imparare",
    "to remember": "ricordare",
    "to forget": "dimenticare",

    # --- Adjectives ---
    "big": "grande",
    "small": "piccolo",
    "beautiful": "bello",
    "ugly": "brutto",
    "new": "nuovo",
    "old": "vecchio",
    "hot": "caldo",
    "cold": "freddo",
    "easy": "facile",
    "difficult": "difficile",
    "fast": "veloce",
    "slow": "lento",
    "happy": "felice",
    "sad": "triste",
    "angry": "arrabbiato",
    "tired": "stanco",
    "hungry": "affamato",
    "thirsty": "assetato",
    "ready": "pronto",
    "open": "aperto",
    "closed": "chiuso",
    "clean": "pulito",
    "dirty": "sporco",
    "expensive": "costoso",
    "cheap": "economico",

    # --- Time Words ---
    "today": "oggi",
    "tomorrow": "domani",
    "yesterday": "ieri",
    "now": "adesso",
    "later": "dopo",
    "soon": "presto",
    "always": "sempre",
    "never": "mai",
    "sometimes": "qualche volta",
    "often": "spesso",
    "morning": "mattina",
    "afternoon": "pomeriggio",
    "evening": "sera",
    "night": "notte",
    "week": "settimana",
    "month": "mese",
    "year": "anno",

    # --- Travel & Directions ---
    "left": "sinistra",
    "right": "destra",
    "straight": "dritto",
    "near": "vicino",
    "far": "lontano",
    "here": "qui",
    "there": "lì",
    "everywhere": "ovunque",
    "reservation": "prenotazione",
    "passport": "passaporto",
    "luggage": "bagaglio",
    "map": "mappa",
    "beach": "spiaggia",
    "mountain": "montagna",
    "train ticket": "biglietto del treno",
    "bus ticket": "biglietto dell'autobus",

    # --- Daily Activities ---
    "to cook": "cucinare",
    "to clean": "pulire",
    "to wash": "lavare",
    "to shower": "fare la doccia",
    "to shave": "radersi",
    "to get dressed": "vestirsi",
    "to wake up": "svegliarsi",
    "to get up": "alzarsi",
    "to sit down": "sedersi",
    "to stand up": "alzarsi in piedi",
    "to leave": "partire",
    "to return": "ritornare",
    "to stay": "stare",
    "to visit": "visitare",
    "to travel": "viaggiare",
    "to plan": "pianificare",
    "to organize": "organizzare",
    "to clean the house": "pulire la casa",
    "to do laundry": "fare il bucato",
    "to iron": "stirare",

    # --- Emotions & States ---
    "excited": "eccitato",
    "bored": "annoiato",
    "worried": "preoccupato",
    "scared": "spaventato",
    "confident": "sicuro",
    "calm": "calmo",
    "nervous": "nervoso",
    "surprised": "sorpreso",
    "proud": "orgoglioso",
    "ashamed": "vergognoso",
    "embarrassed": "imbarazzato",
    "grateful": "grato",
    "jealous": "geloso",
    "curious": "curioso",
    "brave": "coraggioso",

    # --- Weather ---
    "weather": "tempo",
    "sun": "sole",
    "rain": "pioggia",
    "snow": "neve",
    "wind": "vento",
    "cloud": "nuvola",
    "storm": "tempesta",
    "fog": "nebbia",
    "hot weather": "tempo caldo",
    "cold weather": "tempo freddo",
    "it's raining": "sta piovendo",
    "it's snowing": "sta nevicando",
    "it's windy": "c'è vento",
    "it's sunny": "c'è il sole",
    "it's cloudy": "è nuvoloso",

    # --- Clothing ---
    "shirt": "camicia",
    "t-shirt": "maglietta",
    "pants": "pantaloni",
    "shorts": "pantaloncini",
    "dress": "vestito",
    "skirt": "gonna",
    "jacket": "giacca",
    "coat": "cappotto",
    "shoes": "scarpe",
    "boots": "stivali",
    "socks": "calzini",
    "hat": "cappello",
    "gloves": "guanti",
    "scarf": "sciarpa",
    "belt": "cintura",
    "sunglasses": "occhiali da sole",
    "suit": "abito",
    "tie": "cravatta",
    "swimsuit": "costume da bagno",

    # --- Colors ---
    "red": "rosso",
    "blue": "blu",
    "green": "verde",
    "yellow": "giallo",
    "orange": "arancione",
    "purple": "viola",
    "pink": "rosa",
    "brown": "marrone",
    "black": "nero",
    "white": "bianco",
    "gray": "grigio",
    "light blue": "azzurro",
    "gold": "oro",
    "silver": "argento",

    # --- Household Items ---
    "kitchen": "cucina",
    "bathroom": "bagno",
    "bedroom": "camera da letto",
    "living room": "soggiorno",
    "lamp": "lampada",
    "couch": "divano",
    "blanket": "coperta",
    "pillow": "cuscino",
    "refrigerator": "frigorifero",
    "oven": "forno",
    "stove": "fornello",
    "microwave": "microonde",
    "sink": "lavandino",
    "shower": "doccia",
    "toilet": "gabinetto",
    "mirror": "specchio",
    "towel": "asciugamano",
    "soap": "sapone",
    "shampoo": "shampoo",
    "toothbrush": "spazzolino",
    "toothpaste": "dentifricio",

    # --- Nature ---
    "tree": "albero",
    "flower": "fiore",
    "grass": "erba",
    "river": "fiume",
    "lake": "lago",
    "sea": "mare",
    "ocean": "oceano",
    "island": "isola",
    "forest": "foresta",
    "mountain": "montagna",
    "valley": "valle",
    "hill": "collina",
    "rock": "roccia",
    "sand": "sabbia",
    "sky": "cielo",
    "star": "stella",
    "moon": "luna",
    "earth": "terra",
    "fire": "fuoco",
    "ice": "ghiaccio",

    # --- Animals ---
    "dog": "cane",
    "cat": "gatto",
    "bird": "uccello",
    "fish (animal)": "pesce",
    "horse": "cavallo",
    "cow": "mucca",
    "pig": "maiale",
    "sheep": "pecora",
    "goat": "capra",
    "chicken": "pollo",
    "duck": "anatra",
    "rabbit": "coniglio",
    "mouse": "topo",
    "bear": "orso",
    "lion": "leone",
    "tiger": "tigre",
    "elephant": "elefante",
    "monkey": "scimmia",
    "snake": "serpente",
    "frog": "rana",

    # --- Transportation ---
    "car": "auto",
    "motorcycle": "motocicletta",
    "bus": "autobus",
    "train": "treno",
    "subway": "metropolitana",
    "tram": "tram",
    "taxi": "taxi",
    "airplane": "aereo",
    "boat": "barca",
    "ship": "nave",
    "bicycle": "bicicletta",
    "scooter": "scooter",
    "helmet": "casco",
    "gasoline": "benzina",
    "driver": "autista",
    "passenger": "passeggero",
    "traffic": "traffico",
    "road": "strada",
    "highway": "autostrada",
    "bridge": "ponte",

    # --- Work & Office ---
    "job": "lavoro",
    "office": "ufficio",
    "meeting": "riunione",
    "boss": "capo",
    "employee": "dipendente",
    "colleague": "collega",
    "project": "progetto",
    "task": "compito",
    "deadline": "scadenza",
    "email": "email",
    "document": "documento",
    "printer": "stampante",
    "paper": "carta",
    "folder": "cartella",
    "desk": "scrivania",
    "chair": "sedia",
    "keyboard": "tastiera",
    "mouse (computer)": "mouse",
    "internet": "internet",
    "password": "password",

    # --- Shopping ---
    "store": "negozio",
    "cashier": "cassiere",
    "customer": "cliente",
    "price": "prezzo",
    "discount": "sconto",
    "receipt": "scontrino",
    "bag": "sacchetto",
    "size": "taglia",
    "small size": "taglia piccola",
    "medium size": "taglia media",
    "large size": "taglia grande",
    "to buy": "comprare",
    "to return (item)": "restituire",
    "to exchange": "cambiare",
    "to choose": "scegliere",
    "to try on": "provare",
    "sale": "saldi",
    "shopping mall": "centro commerciale",

      # --- Health & Body ---
    "head": "testa",
    "face": "viso",
    "hair": "capelli",
    "eye": "occhio",
    "ear": "orecchio",
    "nose": "naso",
    "mouth": "bocca",
    "tooth": "dente",
    "neck": "collo",
    "shoulder": "spalla",
    "arm": "braccio",
    "hand": "mano",
    "finger": "dito",
    "chest": "petto",
    "back": "schiena",
    "stomach": "stomaco",
    "leg": "gamba",
    "knee": "ginocchio",
    "foot": "piede",
    "heart": "cuore",
    "blood": "sangue",
    "medicine": "medicina",
    "pill": "pillola",
    "doctor's appointment": "appuntamento dal medico",
    "pain": "dolore",
    "headache": "mal di testa",
    "fever": "febbre",
    "cough": "tosse",
    "cold (illness)": "raffreddore",
    "allergy": "allergia",

    # --- Household Chores ---
    "to sweep": "spazzare",
    "to mop": "passare il mocio",
    "to vacuum": "passare l'aspirapolvere",
    "to dust": "spolverare",
    "to fold clothes": "piegare i vestiti",
    "to water plants": "innaffiare le piante",
    "to take out the trash": "portare fuori la spazzatura",
    "to wash dishes": "lavare i piatti",
    "to set the table": "apparecchiare la tavola",
    "to clear the table": "sparecchiare la tavola",

    # --- Technology ---
    "phone charger": "caricatore del telefono",
    "battery": "batteria",
    "screen": "schermo",
    "app": "app",
    "message": "messaggio",
    "call": "chiamata",
    "to text": "mandare un messaggio",
    "to call": "telefonare",
    "to download": "scaricare",
    "to upload": "caricare",
    "to connect": "connettere",
    "to disconnect": "disconnettere",
    "wifi": "wifi",
    "password": "password",
    "settings": "impostazioni",

    # --- Education ---
    "classroom": "aula",
    "lesson": "lezione",
    "homework": "compiti",
    "test": "esame",
    "grade": "voto",
    "teacher": "insegnante",
    "student": "studente",
    "subject": "materia",
    "math": "matematica",
    "science": "scienze",
    "history": "storia",
    "geography": "geografia",
    "language": "lingua",
    "dictionary": "dizionario",
    "notebook": "quaderno",
    "pencil": "matita",
    "eraser": "gomma",
    "backpack": "zaino",

    # --- Advanced Verbs ---
    "to improve": "migliorare",
    "to reduce": "ridurre",
    "to increase": "aumentare",
    "to decide": "decidere",
    "to choose": "scegliere",
    "to explain": "spiegare",
    "to describe": "descrivere",
    "to compare": "confrontare",
    "to build": "costruire",
    "to break": "rompere",
    "to fix": "aggiustare",
    "to create": "creare",
    "to design": "progettare",
    "to develop": "sviluppare",
    "to test": "testare",
    "to measure": "misurare",
    "to prepare": "preparare",
    "to cook": "cucinare",
    "to share": "condividere",
    "to send": "inviare",

    # --- Feelings & Descriptions ---
    "strong": "forte",
    "weak": "debole",
    "healthy": "sano",
    "sick": "malato",
    "friendly": "amichevole",
    "unfriendly": "scortese",
    "funny": "divertente",
    "serious": "serio",
    "smart": "intelligente",
    "stupid": "stupido",
    "polite": "educato",
    "rude": "maleducato",
    "quiet": "silenzioso",
    "loud": "rumoroso",
    "rich": "ricco",
    "poor": "povero",

    # --- Travel & Tourism ---
    "tourist": "turista",
    "guide": "guida",
    "museum": "museo",
    "ticket office": "biglietteria",
    "entrance": "ingresso",
    "exit": "uscita",
    "opening hours": "orari di apertura",
    "closed today": "chiuso oggi",
    "open daily": "aperto tutti i giorni",
    "reservation required": "prenotazione obbligatoria",
    "tour": "visita",
    "map": "mappa",
    "souvenir": "souvenir",
    "photo": "foto",
    "camera": "macchina fotografica",
    "to visit": "visitare",
    "to explore": "esplorare",
    "to travel": "viaggiare",
    "to book": "prenotare",

    # --- Food & Cooking ---
    "breakfast": "colazione",
    "lunch": "pranzo",
    "dinner": "cena",
    "snack": "spuntino",
    "meal": "pasto",
    "fork": "forchetta",
    "knife": "coltello",
    "spoon": "cucchiaio",
    "plate": "piatto",
    "cup": "tazza",
    "glass": "bicchiere",
    "napkin": "tovagliolo",
    "salt": "sale",
    "pepper": "pepe",
    "oil": "olio",
    "vinegar": "aceto",
    "sugar": "zucchero",
    "butter": "burro",
    "egg": "uovo",
    "chicken": "pollo",
    "beef": "manzo",
    "pork": "maiale",
    "vegetarian": "vegetariano",
    "vegan": "vegano",
    "gluten-free": "senza glutine",
    "bill please": "il conto per favore",
    "menu": "menu",
    "waiter": "cameriere",
    "waitress": "cameriera",

    # --- Advanced Phrases ---
    "I'm looking for": "sto cercando",
    "I'm waiting for": "sto aspettando",
    "I'm thinking about it": "ci sto pensando",
    "I changed my mind": "ho cambiato idea",
    "I agree with you": "sono d'accordo con te",
    "I disagree with you": "non sono d'accordo con te",
    "that depends": "dipende",
    "it's not important": "non è importante",
    "it's very important": "è molto importante",
    "I don't care": "non mi importa",
    "I need more time": "ho bisogno di più tempo",
    "I'm almost ready": "sono quasi pronto",
    "I'm not sure": "non sono sicuro",
    "I'm sure": "sono sicuro",
    "I hope so": "lo spero",
    "I hope not": "spero di no",
    "I promise": "prometto",
    "I forgot": "ho dimenticato",
    "I remembered": "mi sono ricordato",

    # --- Numbers 1–50 ---
    "one": "uno",
    "two": "due",
    "three": "tre",
    "four": "quattro",
    "five": "cinque",
    "six": "sei",
    "seven": "sette",
    "eight": "otto",
    "nine": "nove",
    "ten": "dieci",
    "eleven": "undici",
    "twelve": "dodici",
    "thirteen": "tredici",
    "fourteen": "quattordici",
    "fifteen": "quindici",
    "sixteen": "sedici",
    "seventeen": "diciassette",
    "eighteen": "diciotto",
    "nineteen": "diciannove",
    "twenty": "venti",
    "thirty": "trenta",
    "forty": "quaranta",
    "fifty": "cinquanta",

    # --- Numbers 51–100 ---
    "fifty-one": "cinquantuno",
    "fifty-two": "cinquantadue",
    "fifty-three": "cinquantatre",
    "fifty-four": "cinquantaquattro",
    "fifty-five": "cinquantacinque",
    "fifty-six": "cinquantasei",
    "fifty-seven": "cinquantasette",
    "fifty-eight": "cinquantotto",
    "fifty-nine": "cinquantanove",
    "sixty": "sessanta",
    "seventy": "settanta",
    "eighty": "ottanta",
    "ninety": "novanta",
    "one hundred": "cento",

    # --- Advanced Time & Scheduling ---
    "appointment": "appuntamento",
    "schedule": "programma",
    "deadline": "scadenza",
    "meeting": "riunione",
    "event": "evento",
    "holiday": "vacanza",
    "weekend": "fine settimana",
    "weekday": "giorno feriale",
    "midnight": "mezzanotte",
    "noon": "mezzogiorno",
    "early": "presto",
    "late": "tardi",

    # --- Abstract Concepts ---
    "idea": "idea",
    "choice": "scelta",
    "change": "cambiamento",
    "problem": "problema",
    "solution": "soluzione",
    "reason": "ragione",
    "purpose": "scopo",
    "truth": "verità",
    "lie": "bugia",
    "dream": "sogno",
    "memory": "memoria",
    "future": "futuro",
    "past": "passato",
    "present": "presente",
    "goal": "obiettivo",
    "plan": "piano",

    # --- Government & Society ---
    "law": "legge",
    "rule": "regola",
    "rights": "diritti",
    "freedom": "libertà",
    "justice": "giustizia",
    "police": "polizia",
    "court": "tribunale",
    "judge": "giudice",
    "citizen": "cittadino",
    "community": "comunità",
    "society": "società",
    "country": "nazione",
    "border": "confine",

    # --- Money & Finance ---
    "bank account": "conto bancario",
    "cash": "contanti",
    "coins": "monete",
    "salary": "stipendio",
    "income": "reddito",
    "expense": "spesa",
    "budget": "budget",
    "loan": "prestito",
    "debt": "debito",
    "tax": "tassa",
    "tip": "mancia",
    "change (money)": "resto",

    # --- Communication ---
    "conversation": "conversazione",
    "question": "domanda",
    "answer": "risposta",
    "explanation": "spiegazione",
    "story": "storia",
    "news": "notizie",
    "information": "informazioni",
    "message": "messaggio",
    "letter": "lettera",
    "email": "email",
    "voice": "voce",
    "silence": "silenzio",

    # --- Emotions (Advanced) ---
    "anxiety": "ansia",
    "fear": "paura",
    "joy": "gioia",
    "hope": "speranza",
    "trust": "fiducia",
    "doubt": "dubbio",
    "anger": "rabbia",
    "peace": "pace",
    "comfort": "conforto",
    "disappointment": "delusione",
    "confidence": "fiducia",
    "motivation": "motivazione",

    # --- Travel (Advanced) ---
    "border control": "controllo di frontiera",
    "customs": "dogana",
    "baggage claim": "ritiro bagagli",
    "boarding pass": "carta d'imbarco",
    "gate": "uscita d'imbarco",
    "delay": "ritardo",
    "arrival": "arrivo",
    "departure": "partenza",
    "round trip": "andata e ritorno",
    "one-way ticket": "biglietto di sola andata",
    "tourist attraction": "attrazione turistica",
    "travel insurance": "assicurazione di viaggio",

    # --- Work (Advanced) ---
    "career": "carriera",
    "promotion": "promozione",
    "experience": "esperienza",
    "skill": "abilità",
    "training": "formazione",
    "interview": "colloquio",
    "resume": "curriculum",
    "contract": "contratto",
    "agreement": "accordo",
    "negotiation": "negoziazione",
    "leadership": "leadership",
    "teamwork": "lavoro di squadra",

    # --- Verbs (Advanced Set 2) ---
    "to negotiate": "negoziare",
    "to organize": "organizzare",
    "to manage": "gestire",
    "to lead": "guidare",
    "to support": "supportare",
    "to recommend": "raccomandare",
    "to warn": "avvertire",
    "to protect": "proteggere",
    "to allow": "permettere",
    "to forbid": "vietare",
    "to promise": "promettere",
    "to apologize": "scusarsi",
    "to celebrate": "celebrare",
    "to relax": "rilassarsi",
    "to rest": "riposare",
    "to succeed": "riuscire",
    "to fail": "fallire",
    "to hope": "sperare",
    "to trust": "fidarsi",
    "to doubt": "dubitare",

    # --- Household (Advanced) ---
    "ceiling": "soffitto",
    "floor": "pavimento",
    "wall": "muro",
    "roof": "tetto",
    "yard": "giardino",
    "garage": "garage",
    "balcony": "balcone",
    "stairs": "scale",
    "elevator": "ascensore",
    "heater": "riscaldamento",
    "air conditioner": "aria condizionata",
    "light switch": "interruttore",
    "outlet": "presa elettrica",

    # --- Food (Advanced) ---
    "flour": "farina",
    "spice": "spezia",
    "herb": "erba aromatica",
    "garlic": "aglio",
    "onion": "cipolla",
    "tomato": "pomodoro",
    "pepper (vegetable)": "peperone",
    "lemon": "limone",
    "grape": "uva",
    "strawberry": "fragola",
    "peach": "pesca",
    "pear": "pera",
    "watermelon": "anguria",
    "melon": "melone",
    "olive": "oliva",
    "mushroom": "fungo",

    # --- Phrases (Advanced) ---
    "what do you mean": "cosa intendi",
    "that makes sense": "ha senso",
    "I appreciate it": "lo apprezzo",
    "I'm not interested": "non sono interessato",
    "I'm interested": "sono interessato",
    "I'm learning Italian": "sto imparando l'italiano",
    "can you help me": "puoi aiutarmi",
    "can you show me": "puoi mostrarmi",
    "can you explain": "puoi spiegare",
    "I don't remember": "non ricordo",
    "I completely agree": "sono completamente d'accordo",
    "I completely disagree": "sono completamente in disaccordo",
    "it's too expensive": "è troppo costoso",
    "it's too far": "è troppo lontano",
    "it's close": "è vicino",
    "it's possible": "è possibile",
    "it's impossible": "è impossibile",
    "I'm almost there": "sono quasi arrivato",
    "I'm on my way": "sto arrivando",
    "let's go": "andiamo",

    # --- Final Set (to reach 1000) ---
    "to borrow": "prendere in prestito",
    "to lend": "prestare",
    "to invite": "invitare",
    "to join": "unirsi",
    "to separate": "separare",
    "to connect": "collegare",
    "to disconnect": "scollegare",
    "to print": "stampare",
    "to sign": "firmare",
    "to cancel": "cancellare",
    "to confirm": "confermare",
    "to guess": "indovinare",
    "to prove": "dimostrare",
    "to argue": "litigare",
    "to forgive": "perdonare",
    "to respect": "rispettare",
    "to admire": "ammirare",
    "to complain": "lamentarsi",
    "to organize": "organizzare",
    "to celebrate": "celebrare",
}



