popular_quotes_summary = [
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': '2 Nephi 2:25',
        'book': '2 Nephi',
        'chapter': '2:25',
        'summary': 'Humanity exists to experience joy.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': '1 Nephi 3:7',
        'book': '1 Nephi',
        'chapter': '3:7',
        'summary': 'God provides a way to accomplish His commandments.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': 'Alma 32:21',
        'book': 'Alma',
        'chapter': '32:21',
        'summary': 'Faith is hope in things unseen but true.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': 'Ether 12:4',
        'book': 'Ether',
        'chapter': '12:4',
        'summary': 'Faith creates a sure hope that anchors the soul.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': 'Moroni 7:33',
        'book': 'Moroni',
        'chapter': '7:33',
        'summary': 'Faith in Christ empowers us to do His will.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': 'Alma 37:46',
        'book': 'Alma',
        'chapter': '37:46',
        'summary': 'Righteousness nourishes and strengthens a community.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': 'Alma 30:44',
        'book': 'Alma',
        'chapter': '30:44',
        'summary': 'All things testify that God exists.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': '2 Nephi 26:12',
        'book': '2 Nephi',
        'chapter': '26:12',
        'summary': 'Christ is the life and light of the world.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': 'Moroni 10:4–5',
        'book': 'Moroni',
        'chapter': '10:4–5',
        'summary': 'Truth is revealed through sincere prayer and the Holy Ghost.',
    },
    {
        'category': '🕊️ Faith & Trust in God',
        'reference': '1 Nephi 10:19',
        'book': '1 Nephi',
        'chapter': '10:19',
        'summary': 'God’s course is eternal; those who seek will find.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': 'Moroni 7:47',
        'book': 'Moroni',
        'chapter': '7:47',
        'summary': 'Charity is the pure love of Christ and endures forever.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': 'Mosiah 2:17',
        'book': 'Mosiah',
        'chapter': '2:17',
        'summary': 'Serving others is serving God.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': 'Mosiah 4:30',
        'book': 'Mosiah',
        'chapter': '4:30',
        'summary': 'Watch your thoughts, words, and deeds to avoid spiritual danger.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': 'Alma 34:40',
        'book': 'Alma',
        'chapter': '34:40',
        'summary': 'Patience and endurance bring peace.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': 'Mosiah 18:8–9',
        'book': 'Mosiah',
        'chapter': '18:8–9',
        'summary': 'Followers of Christ bear one another’s burdens.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': 'Ether 12:27',
        'book': 'Ether',
        'chapter': '12:27',
        'summary': 'Weakness becomes strength through humility and Christ’s grace.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': '3 Nephi 12:44',
        'book': '3 Nephi',
        'chapter': '12:44',
        'summary': 'Love your enemies and pray for them.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': 'Alma 7:12',
        'book': 'Alma',
        'chapter': '7:12',
        'summary': 'Christ understands our pains and succors us.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': 'Mosiah 3:19',
        'book': 'Mosiah',
        'chapter': '3:19',
        'summary': 'Put off the natural man and become childlike through Christ.',
    },
    {
        'category': '❤️ Charity, Love & Compassion',
        'reference': '3 Nephi 11:29',
        'book': '3 Nephi',
        'chapter': '11:29',
        'summary': 'Contention is not of Christ.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': 'Alma 36:3',
        'book': 'Alma',
        'chapter': '36:3',
        'summary': 'Trusting God brings support in trials.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': 'Mosiah 24:14',
        'book': 'Mosiah',
        'chapter': '24:14',
        'summary': 'God eases burdens and strengthens us.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': 'Alma 38:5',
        'book': 'Alma',
        'chapter': '38:5',
        'summary': 'God supports those who trust Him.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': 'Helaman 5:12',
        'book': 'Helaman',
        'chapter': '5:12',
        'summary': 'Build your foundation on Christ to withstand adversity.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': '3 Nephi 22:7',
        'book': '3 Nephi',
        'chapter': '22:7',
        'summary': 'God’s mercy is everlasting.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': 'Ether 12:6',
        'book': 'Ether',
        'chapter': '12:6',
        'summary': 'Faith is tested before miracles come.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': 'Alma 26:12',
        'book': 'Alma',
        'chapter': '26:12',
        'summary': 'Strength comes from God, not ourselves.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': 'Mosiah 2:41',
        'book': 'Mosiah',
        'chapter': '2:41',
        'summary': 'Obedience brings happiness and protection.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': 'Alma 58:11',
        'book': 'Alma',
        'chapter': '58:11',
        'summary': 'God gives peace and courage in danger.',
    },
    {
        'category': '✨ Hope, Peace & Endurance',
        'reference': '3 Nephi 1:13',
        'book': '3 Nephi',
        'chapter': '1:13',
        'summary': 'God fulfills His promises.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': 'Alma 46:12',
        'book': 'Alma',
        'chapter': '46:12',
        'summary': 'Captain Moroni raises the Title of Liberty to defend faith and family.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': 'Alma 53:20',
        'book': 'Alma',
        'chapter': '53:20',
        'summary': 'The stripling warriors are valiant and trustworthy.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': 'Alma 48:17',
        'book': 'Alma',
        'chapter': '48:17',
        'summary': 'Moroni’s righteousness would shake hell itself.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': 'Mosiah 2:22',
        'book': 'Mosiah',
        'chapter': '2:22',
        'summary': 'God blesses those who keep His commandments.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': '3 Nephi 12:16',
        'book': '3 Nephi',
        'chapter': '12:16',
        'summary': 'Let your light shine to glorify God.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': 'Alma 43:47',
        'book': 'Alma',
        'chapter': '43:47',
        'summary': 'Defending family and liberty is justified.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': 'Mosiah 29:26',
        'book': 'Mosiah',
        'chapter': '29:26',
        'summary': 'Majority rule is safer than tyranny.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': 'Alma 60:36',
        'book': 'Alma',
        'chapter': '60:36',
        'summary': 'Moroni’s integrity in leadership.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': '3 Nephi 12:9',
        'book': '3 Nephi',
        'chapter': '12:9',
        'summary': 'Peacemakers are blessed.',
    },
    {
        'category': '🔥 Courage, Duty & Righteous Action',
        'reference': 'Alma 17:11',
        'book': 'Alma',
        'chapter': '17:11',
        'summary': 'Missionaries become instruments in God’s hands.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': '2 Nephi 32:3',
        'book': '2 Nephi',
        'chapter': '32:3',
        'summary': 'Angels speak by the power of the Holy Ghost.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': 'Alma 12:9',
        'book': 'Alma',
        'chapter': '12:9',
        'summary': 'God reveals mysteries according to faithfulness.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': 'Jacob 4:10',
        'book': 'Jacob',
        'chapter': '4:10',
        'summary': 'Don’t counsel God; seek His counsel.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': 'Mosiah 8:18',
        'book': 'Mosiah',
        'chapter': '8:18',
        'summary': 'God gives power to work mighty miracles.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': '3 Nephi 18:20',
        'book': '3 Nephi',
        'chapter': '18:20',
        'summary': 'Ask in Christ’s name and receive according to God’s will.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': 'Moroni 7:16',
        'book': 'Moroni',
        'chapter': '7:16',
        'summary': 'The Spirit helps discern good from evil.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': 'Alma 32:28',
        'book': 'Alma',
        'chapter': '32:28',
        'summary': 'Faith grows like a seed when nourished.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': 'Ether 3:14',
        'book': 'Ether',
        'chapter': '3:14',
        'summary': 'Christ reveals Himself as God’s Son.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': '3 Nephi 11:10–11',
        'book': '3 Nephi',
        'chapter': '11:10–11',
        'summary': 'Christ declares His divine mission.',
    },
    {
        'category': '📖 Truth, Revelation & Knowledge',
        'reference': 'Moroni 10:32',
        'book': 'Moroni',
        'chapter': '10:32',
        'summary': 'Love God fully and be perfected in Christ.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Alma 11:37',
        'book': 'Alma',
        'chapter': '11:37',
        'summary': 'Salvation requires repentance.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Alma 5:14',
        'book': 'Alma',
        'chapter': '5:14',
        'summary': 'Spiritual rebirth changes the heart.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Mosiah 4:10',
        'book': 'Mosiah',
        'chapter': '4:10',
        'summary': 'Repent sincerely and forsake sin.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Alma 42:27',
        'book': 'Alma',
        'chapter': '42:27',
        'summary': 'Mercy is offered, but we must choose it.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Helaman 12:3',
        'book': 'Helaman',
        'chapter': '12:3',
        'summary': 'Hardship often brings people back to God.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Alma 7:11',
        'book': 'Alma',
        'chapter': '7:11',
        'summary': 'Christ suffers pains and afflictions for all.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Mosiah 26:30',
        'book': 'Mosiah',
        'chapter': '26:30',
        'summary': 'God forgives those who repent.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Alma 36:24',
        'book': 'Alma',
        'chapter': '36:24',
        'summary': 'Sharing the joy of redemption.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': '3 Nephi 9:22',
        'book': '3 Nephi',
        'chapter': '9:22',
        'summary': 'Christ invites all to come unto Him.',
    },
    {
        'category': '🌿 Repentance, Change & Forgiveness',
        'reference': 'Moroni 6:8',
        'book': 'Moroni',
        'chapter': '6:8',
        'summary': 'Repeated repentance is accepted.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': 'Ether 3:14',
        'book': 'Ether',
        'chapter': '3:14',
        'summary': 'We are children of God.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': 'Alma 34:32',
        'book': 'Alma',
        'chapter': '34:32',
        'summary': 'This life is the time to prepare to meet God.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': '2 Nephi 9:28',
        'book': '2 Nephi',
        'chapter': '9:28',
        'summary': 'Learning is good, but pride is dangerous.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': 'Jacob 2:18',
        'book': 'Jacob',
        'chapter': '2:18',
        'summary': 'Seek God first before riches.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': 'Mosiah 2:20',
        'book': 'Mosiah',
        'chapter': '2:20',
        'summary': 'We are indebted to God for all blessings.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': 'Alma 12:24',
        'book': 'Alma',
        'chapter': '12:24',
        'summary': 'Mortality is a probationary state.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': '3 Nephi 27:27',
        'book': '3 Nephi',
        'chapter': '27:27',
        'summary': 'Judge righteously, as Christ judges.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': 'Moroni 7:48',
        'book': 'Moroni',
        'chapter': '7:48',
        'summary': 'Pray to be filled with Christlike love.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': 'Alma 40:11',
        'book': 'Alma',
        'chapter': '40:11',
        'summary': 'Spirits return to God after death.',
    },
    {
        'category': '🌅 Purpose, Identity & Eternal Perspective',
        'reference': '2 Nephi 31:20',
        'book': '2 Nephi',
        'chapter': '31:20',
        'summary': 'Endure to the end with steadfast faith.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 46:12',
        'book': 'Alma',
        'chapter': '46:12',
        'summary': 'Title of Liberty defends faith and freedom.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 48:11',
        'book': 'Alma',
        'chapter': '48:11',
        'summary': 'Moroni is firm in faith and duty.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 43:30',
        'book': 'Alma',
        'chapter': '43:30',
        'summary': 'Use wisdom and courage in defense.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 60:13',
        'book': 'Alma',
        'chapter': '60:13',
        'summary': 'Neglecting duty brings condemnation.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 62:41',
        'book': 'Alma',
        'chapter': '62:41',
        'summary': 'Trials can harden or soften hearts.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': '3 Nephi 3:12',
        'book': '3 Nephi',
        'chapter': '3:12',
        'summary': 'Unity protects against enemies.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 44:4',
        'book': 'Alma',
        'chapter': '44:4',
        'summary': 'God supports righteous defense.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 56:47',
        'book': 'Alma',
        'chapter': '56:47',
        'summary': 'Mothers taught the stripling warriors faith.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 57:21',
        'book': 'Alma',
        'chapter': '57:21',
        'summary': 'Exact obedience brings miracles.',
    },
    {
        'category': '⚔️ War, Liberty & Leadership',
        'reference': 'Alma 43:48',
        'book': 'Alma',
        'chapter': '43:48',
        'summary': 'Courage comes from faith.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': '3 Nephi 11:10–11',
        'book': '3 Nephi',
        'chapter': '11:10–11',
        'summary': 'Christ announces His divine mission.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': 'Alma 7:11–12',
        'book': 'Alma',
        'chapter': '7:11–12',
        'summary': 'Christ suffers all pains to succor His people.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': 'Mosiah 15:9',
        'book': 'Mosiah',
        'chapter': '15:9',
        'summary': 'Christ stands between justice and mercy.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': '3 Nephi 17:7',
        'book': '3 Nephi',
        'chapter': '17:7',
        'summary': 'Christ heals the afflicted.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': '3 Nephi 18:21',
        'book': '3 Nephi',
        'chapter': '18:21',
        'summary': 'Pray always as families.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': '3 Nephi 27:13',
        'book': '3 Nephi',
        'chapter': '27:13',
        'summary': 'Christ explains His gospel.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': 'Mosiah 3:8',
        'book': 'Mosiah',
        'chapter': '3:8',
        'summary': 'Christ will come to redeem His people.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': 'Alma 42:15',
        'book': 'Alma',
        'chapter': '42:15',
        'summary': 'Atonement satisfies justice and extends mercy.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': '2 Nephi 25:26',
        'book': '2 Nephi',
        'chapter': '25:26',
        'summary': 'We talk, rejoice, and preach of Christ.',
    },
    {
        'category': '🌟 Christ’s Ministry & Atonement',
        'reference': 'Moroni 10:32',
        'book': 'Moroni',
        'chapter': '10:32',
        'summary': 'Be perfected in Christ through love.',
    },
]
