quotes_data = [
    # Faith & Trust in God
    {'quote': 'Humanity exists to experience joy.', 'speaker': '', 'book': '2 Nephi', 'chapter': '2:25', 'hints': ['Faith & Trust in God', 'source: https://addfaith.org/blog/faith/gospel-doctrine/essential-book-of-mormon-scriptures-faith/']},
    {'quote': 'God provides a way to accomplish His commandments.', 'speaker': '', 'book': '1 Nephi', 'chapter': '3:7', 'hints': ['Faith & Trust in God', 'source: https://addfaith.org/blog/faith/gospel-doctrine/essential-book-of-mormon-scriptures-faith/']},
    {'quote': 'Faith is hope in things unseen but true.', 'speaker': '', 'book': 'Alma', 'chapter': '32:21', 'hints': ['Faith & Trust in God', 'source: https://snugfam.com/best-quotes-from-the-book-of-mormon-timeless-wisdom-for-life/']},
    {'quote': 'Faith creates a sure hope that anchors the soul.', 'speaker': '', 'book': 'Ether', 'chapter': '12:4', 'hints': ['Faith & Trust in God', 'source: https://snugfam.com/best-quotes-from-the-book-of-mormon-timeless-wisdom-for-life/']},
    {'quote': 'Faith in Christ empowers us to do His will.', 'speaker': '', 'book': 'Moroni', 'chapter': '7:33', 'hints': ['Faith & Trust in God', 'source: https://snugfam.com/best-quotes-from-the-book-of-mormon-timeless-wisdom-for-life/']},
    {'quote': 'Righteousness nourishes and strengthens a community.', 'speaker': '', 'book': 'Alma', 'chapter': '37:46', 'hints': ['Faith & Trust in God', 'source: https://scripturesavvy.com/book-of-mormon-quotes/']},
    {'quote': 'All things testify that God exists.', 'speaker': '', 'book': 'Alma', 'chapter': '30:44', 'hints': ['Faith & Trust in God', 'source: https://scripturesavvy.com/book-of-mormon-quotes/']},
    {'quote': 'Christ is the life and light of the world.', 'speaker': '', 'book': '2 Nephi', 'chapter': '26:12', 'hints': ['Faith & Trust in God', 'source: https://scripturesavvy.com/book-of-mormon-quotes/']},
    {'quote': 'Truth is revealed through sincere prayer and the Holy Ghost.', 'speaker': '', 'book': 'Moroni', 'chapter': '10:4-5', 'hints': ['Faith & Trust in God', 'source: https://addfaith.org/blog/faith/gospel-doctrine/essential-book-of-mormon-scriptures-faith/']},
    {'quote': 'God\u2019s course is eternal; those who seek will find.', 'speaker': '', 'book': '1 Nephi', 'chapter': '10:19', 'hints': ['Faith & Trust in God', 'source: https://bookroo.com/quotes/the-book-of-mormon']},

    # Charity, Love & Compassion
    {'quote': 'Charity is the pure love of Christ and endures forever.', 'speaker': '', 'book': 'Moroni', 'chapter': '7:47', 'hints': ['Charity, Love & Compassion', 'source: https://bookroo.com/quotes/the-book-of-mormon']},
    {'quote': 'Serving others is serving God.', 'speaker': '', 'book': 'Mosiah', 'chapter': '2:17', 'hints': ['Charity, Love & Compassion']},
    {'quote': 'Watch your thoughts, words, and deeds to avoid spiritual danger.', 'speaker': '', 'book': 'Mosiah', 'chapter': '4:30', 'hints': ['Charity, Love & Compassion']},
    {'quote': 'Patience and endurance bring peace.', 'speaker': '', 'book': 'Alma', 'chapter': '34:40', 'hints': ['Charity, Love & Compassion']},
    {'quote': 'Followers of Christ bear one another\u2019s burdens.', 'speaker': '', 'book': 'Mosiah', 'chapter': '18:8-9', 'hints': ['Charity, Love & Compassion']},
    {'quote': 'Weakness becomes strength through humility and Christ\u2019s grace.', 'speaker': '', 'book': 'Ether', 'chapter': '12:27', 'hints': ['Charity, Love & Compassion']},
    {'quote': 'Love your enemies and pray for them.', 'speaker': '', 'book': '3 Nephi', 'chapter': '12:44', 'hints': ['Charity, Love & Compassion']},
    {'quote': 'Christ understands our pains and succors us.', 'speaker': '', 'book': 'Alma', 'chapter': '7:12', 'hints': ['Charity, Love & Compassion', 'source: https://addfaith.org/blog/faith/gospel-doctrine/essential-book-of-mormon-scriptures-faith/']},
    {'quote': 'Put off the natural man and become childlike through Christ.', 'speaker': '', 'book': 'Mosiah', 'chapter': '3:19', 'hints': ['Charity, Love & Compassion', 'source: https://addfaith.org/blog/faith/gospel-doctrine/essential-book-of-mormon-scriptures-faith/']},
    {'quote': 'Contention is not of Christ.', 'speaker': '', 'book': '3 Nephi', 'chapter': '11:29', 'hints': ['Charity, Love & Compassion']},

    # Hope, Peace & Endurance
    {'quote': 'Trusting God brings support in trials.', 'speaker': '', 'book': 'Alma', 'chapter': '36:3', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'God eases burdens and strengthens us.', 'speaker': '', 'book': 'Mosiah', 'chapter': '24:14', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'God supports those who trust Him.', 'speaker': '', 'book': 'Alma', 'chapter': '38:5', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'Build your foundation on Christ to withstand adversity.', 'speaker': '', 'book': 'Helaman', 'chapter': '5:12', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'God\u2019s mercy is everlasting.', 'speaker': '', 'book': '3 Nephi', 'chapter': '22:7', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'Faith is tested before miracles come.', 'speaker': '', 'book': 'Ether', 'chapter': '12:6', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'Strength comes from God, not ourselves.', 'speaker': '', 'book': 'Alma', 'chapter': '26:12', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'Obedience brings happiness and protection.', 'speaker': '', 'book': 'Mosiah', 'chapter': '2:41', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'God gives peace and courage in danger.', 'speaker': '', 'book': 'Alma', 'chapter': '58:11', 'hints': ['Hope, Peace & Endurance']},
    {'quote': 'God fulfills His promises.', 'speaker': '', 'book': '3 Nephi', 'chapter': '1:13', 'hints': ['Hope, Peace & Endurance']},

    # Courage, Duty & Righteous Action
    {'quote': 'Captain Moroni raises the Title of Liberty to defend faith and family.', 'speaker': '', 'book': 'Alma', 'chapter': '46:12', 'hints': ['Courage, Duty & Righteous Action', 'source: https://bookroo.com/quotes/the-book-of-mormon']},
    {'quote': 'The stripling warriors are valiant and trustworthy.', 'speaker': '', 'book': 'Alma', 'chapter': '53:20', 'hints': ['Courage, Duty & Righteous Action']},
    {'quote': 'Moroni\u2019s righteousness would shake hell itself.', 'speaker': '', 'book': 'Alma', 'chapter': '48:17', 'hints': ['Courage, Duty & Righteous Action']},
    {'quote': 'God blesses those who keep His commandments.', 'speaker': '', 'book': 'Mosiah', 'chapter': '2:22', 'hints': ['Courage, Duty & Righteous Action']},
    {'quote': 'Let your light shine to glorify God.', 'speaker': '', 'book': '3 Nephi', 'chapter': '12:16', 'hints': ['Courage, Duty & Righteous Action']},
    {'quote': 'Defending family and liberty is justified.', 'speaker': '', 'book': 'Alma', 'chapter': '43:47', 'hints': ['Courage, Duty & Righteous Action']},
    {'quote': 'Majority rule is safer than tyranny.', 'speaker': '', 'book': 'Mosiah', 'chapter': '29:26', 'hints': ['Courage, Duty & Righteous Action']},
    {'quote': 'Moroni\u2019s integrity in leadership.', 'speaker': '', 'book': 'Alma', 'chapter': '60:36', 'hints': ['Courage, Duty & Righteous Action']},
    {'quote': 'Peacemakers are blessed.', 'speaker': '', 'book': '3 Nephi', 'chapter': '12:9', 'hints': ['Courage, Duty & Righteous Action']},
    {'quote': 'Missionaries become instruments in God\u2019s hands.', 'speaker': '', 'book': 'Alma', 'chapter': '17:11', 'hints': ['Courage, Duty & Righteous Action']},

    # Truth, Revelation & Knowledge
    {'quote': 'Angels speak by the power of the Holy Ghost.', 'speaker': '', 'book': '2 Nephi', 'chapter': '32:3', 'hints': ['Truth, Revelation & Knowledge']},
    {'quote': 'God reveals mysteries according to faithfulness.', 'speaker': '', 'book': 'Alma', 'chapter': '12:9', 'hints': ['Truth, Revelation & Knowledge']},
    {'quote': 'Don\u2019t counsel God; seek His counsel.', 'speaker': '', 'book': 'Jacob', 'chapter': '4:10', 'hints': ['Truth, Revelation & Knowledge']},
    {'quote': 'God gives power to work mighty miracles.', 'speaker': '', 'book': 'Mosiah', 'chapter': '8:18', 'hints': ['Truth, Revelation & Knowledge']},
    {'quote': 'Ask in Christ\u2019s name and receive according to God\u2019s will.', 'speaker': '', 'book': '3 Nephi', 'chapter': '18:20', 'hints': ['Truth, Revelation & Knowledge']},
    {'quote': 'The Spirit helps discern good from evil.', 'speaker': '', 'book': 'Moroni', 'chapter': '7:16', 'hints': ['Truth, Revelation & Knowledge']},
    {'quote': 'Faith grows like a seed when nourished.', 'speaker': '', 'book': 'Alma', 'chapter': '32:28', 'hints': ['Truth, Revelation & Knowledge', 'source: https://addfaith.org/blog/faith/gospel-doctrine/essential-book-of-mormon-scriptures-faith/']},
    {'quote': 'Christ reveals Himself as God\u2019s Son.', 'speaker': '', 'book': 'Ether', 'chapter': '3:14', 'hints': ['Truth, Revelation & Knowledge', 'source: https://scripturesavvy.com/book-of-mormon-quotes/']},
    {'quote': 'Christ declares His divine mission.', 'speaker': '', 'book': '3 Nephi', 'chapter': '11:10-11', 'hints': ['Truth, Revelation & Knowledge', 'source: https://addfaith.org/blog/faith/gospel-doctrine/essential-book-of-mormon-scriptures-faith/']},
    {'quote': 'Love God fully and be perfected in Christ.', 'speaker': '', 'book': 'Moroni', 'chapter': '10:32', 'hints': ['Truth, Revelation & Knowledge']},

    # Repentance, Change & Forgiveness
    {'quote': 'Salvation requires repentance.', 'speaker': '', 'book': 'Alma', 'chapter': '11:37', 'hints': ['Repentance, Change & Forgiveness', 'source: https://scripturesavvy.com/book-of-mormon-quotes/']},
    {'quote': 'Spiritual rebirth changes the heart.', 'speaker': '', 'book': 'Alma', 'chapter': '5:14', 'hints': ['Repentance, Change & Forgiveness']},
    {'quote': 'Repent sincerely and forsake sin.', 'speaker': '', 'book': 'Mosiah', 'chapter': '4:10', 'hints': ['Repentance, Change & Forgiveness']},
    {'quote': 'Mercy is offered, but we must choose it.', 'speaker': '', 'book': 'Alma', 'chapter': '42:27', 'hints': ['Repentance, Change & Forgiveness']},
    {'quote': 'Hardship often brings people back to God.', 'speaker': '', 'book': 'Helaman', 'chapter': '12:3', 'hints': ['Repentance, Change & Forgiveness']},
    {'quote': 'Christ suffers pains and afflictions for all.', 'speaker': '', 'book': 'Alma', 'chapter': '7:11', 'hints': ['Repentance, Change & Forgiveness', 'source: https://www.goodreads.com/work/quotes/2139868-the-book-of-mormon']},
    {'quote': 'God forgives those who repent.', 'speaker': '', 'book': 'Mosiah', 'chapter': '26:30', 'hints': ['Repentance, Change & Forgiveness']},
    {'quote': 'Sharing the joy of redemption.', 'speaker': '', 'book': 'Alma', 'chapter': '36:24', 'hints': ['Repentance, Change & Forgiveness']},
    {'quote': 'Christ invites all to come unto Him.', 'speaker': '', 'book': '3 Nephi', 'chapter': '9:22', 'hints': ['Repentance, Change & Forgiveness']},
    {'quote': 'Repeated repentance is accepted.', 'speaker': '', 'book': 'Moroni', 'chapter': '6:8', 'hints': ['Repentance, Change & Forgiveness']},

    # Purpose, Identity & Eternal Perspective
    {'quote': 'We are children of God.', 'speaker': '', 'book': 'Ether', 'chapter': '3:14', 'hints': ['Purpose, Identity & Eternal Perspective', 'source: https://scripturesavvy.com/book-of-mormon-quotes/']},
    {'quote': 'This life is the time to prepare to meet God.', 'speaker': '', 'book': 'Alma', 'chapter': '34:32', 'hints': ['Purpose, Identity & Eternal Perspective']},
    {'quote': 'Learning is good, but pride is dangerous.', 'speaker': '', 'book': '2 Nephi', 'chapter': '9:28', 'hints': ['Purpose, Identity & Eternal Perspective']},
    {'quote': 'Seek God first before riches.', 'speaker': '', 'book': 'Jacob', 'chapter': '2:18', 'hints': ['Purpose, Identity & Eternal Perspective']},
    {'quote': 'We are indebted to God for all blessings.', 'speaker': '', 'book': 'Mosiah', 'chapter': '2:20', 'hints': ['Purpose, Identity & Eternal Perspective']},
    {'quote': 'Mortality is a probationary state.', 'speaker': '', 'book': 'Alma', 'chapter': '12:24', 'hints': ['Purpose, Identity & Eternal Perspective']},
    {'quote': 'Judge righteously, as Christ judges.', 'speaker': '', 'book': '3 Nephi', 'chapter': '27:27', 'hints': ['Purpose, Identity & Eternal Perspective']},
    {'quote': 'Pray to be filled with Christlike love.', 'speaker': '', 'book': 'Moroni', 'chapter': '7:48', 'hints': ['Purpose, Identity & Eternal Perspective']},
    {'quote': 'Spirits return to God after death.', 'speaker': '', 'book': 'Alma', 'chapter': '40:11', 'hints': ['Purpose, Identity & Eternal Perspective']},
    {'quote': 'Endure to the end with steadfast faith.', 'speaker': '', 'book': '2 Nephi', 'chapter': '31:20', 'hints': ['Purpose, Identity & Eternal Perspective']},

    # War, Liberty & Leadership
    {'quote': 'Title of Liberty defends faith and freedom.', 'speaker': '', 'book': 'Alma', 'chapter': '46:12', 'hints': ['War, Liberty & Leadership', 'source: https://bookroo.com/quotes/the-book-of-mormon']},
    {'quote': 'Moroni is firm in faith and duty.', 'speaker': '', 'book': 'Alma', 'chapter': '48:11', 'hints': ['War, Liberty & Leadership']},
    {'quote': 'Use wisdom and courage in defense.', 'speaker': '', 'book': 'Alma', 'chapter': '43:30', 'hints': ['War, Liberty & Leadership']},
    {'quote': 'Neglecting duty brings condemnation.', 'speaker': '', 'book': 'Alma', 'chapter': '60:13', 'hints': ['War, Liberty & Leadership']},
    {'quote': 'Trials can harden or soften hearts.', 'speaker': '', 'book': 'Alma', 'chapter': '62:41', 'hints': ['War, Liberty & Leadership']},
    {'quote': 'Unity protects against enemies.', 'speaker': '', 'book': '3 Nephi', 'chapter': '3:12', 'hints': ['War, Liberty & Leadership']},
    {'quote': 'God supports righteous defense.', 'speaker': '', 'book': 'Alma', 'chapter': '44:4', 'hints': ['War, Liberty & Leadership']},
    {'quote': 'Mothers taught the stripling warriors faith.', 'speaker': '', 'book': 'Alma', 'chapter': '56:47', 'hints': ['War, Liberty & Leadership']},
    {'quote': 'Exact obedience brings miracles.', 'speaker': '', 'book': 'Alma', 'chapter': '57:21', 'hints': ['War, Liberty & Leadership']},
    {'quote': 'Courage comes from faith.', 'speaker': '', 'book': 'Alma', 'chapter': '43:48', 'hints': ['War, Liberty & Leadership']},

    # Christ\u2019s Ministry & Atonement
    {'quote': 'Christ announces His divine mission.', 'speaker': '', 'book': '3 Nephi', 'chapter': '11:10-11', 'hints': ['Christ\u2019s Ministry & Atonement', 'source: https://addfaith.org/blog/faith/gospel-doctrine/essential-book-of-mormon-scriptures-faith/']},
    {'quote': 'Christ suffers all pains to succor His people.', 'speaker': '', 'book': 'Alma', 'chapter': '7:11-12', 'hints': ['Christ\u2019s Ministry & Atonement', 'source: https://www.goodreads.com/work/quotes/2139868-the-book-of-mormon']},
    {'quote': 'Christ stands between justice and mercy.', 'speaker': '', 'book': 'Mosiah', 'chapter': '15:9', 'hints': ['Christ\u2019s Ministry & Atonement']},
    {'quote': 'Christ heals the afflicted.', 'speaker': '', 'book': '3 Nephi', 'chapter': '17:7', 'hints': ['Christ\u2019s Ministry & Atonement']},
    {'quote': 'Pray always as families.', 'speaker': '', 'book': '3 Nephi', 'chapter': '18:21', 'hints': ['Christ\u2019s Ministry & Atonement']},
    {'quote': 'Christ explains His gospel.', 'speaker': '', 'book': '3 Nephi', 'chapter': '27:13', 'hints': ['Christ\u2019s Ministry & Atonement']},
    {'quote': 'Christ will come to redeem His people.', 'speaker': '', 'book': 'Mosiah', 'chapter': '3:8', 'hints': ['Christ\u2019s Ministry & Atonement']},
    {'quote': 'Atonement satisfies justice and extends mercy.', 'speaker': '', 'book': 'Alma', 'chapter': '42:15', 'hints': ['Christ\u2019s Ministry & Atonement']},
    {'quote': 'We talk, rejoice, and preach of Christ.', 'speaker': '', 'book': '2 Nephi', 'chapter': '25:26', 'hints': ['Christ\u2019s Ministry & Atonement']},
    {'quote': 'Be perfected in Christ through love.', 'speaker': '', 'book': 'Moroni', 'chapter': '10:32', 'hints': ['Christ\u2019s Ministry & Atonement']},
]
